name: agitprint
description: o App da melhor agencia do Brasil.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_storage: ^8.0.0
  image_picker: ^0.7.2
  shared_preferences: ^2.0.3
  google_fonts:
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.0.3
  multi_select_flutter: ^3.1.8
  brasil_fields: ^1.0.0
  cpfcnpj: ^1.0.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
     - assets/images/
     - assets/icons/
     - assets/json/

